title = "Gitleaks config"

[allowlist]
description = "Exclude common safe patterns"
regexes = [
  '''(?i)dummy[_-]?secret''',
  '''(?i)1234567890abcdef'''
]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key\s*[:=]\s*["']?[A-Za-z0-9_\-]{16,})'''
tags = ["key", "api", "generic"]
